# Generated by Django 5.0.1 on 2024-04-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Задача')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('task_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timemanagment.category', verbose_name='Категория')),
            ],
        ),
    ]
